#
# Copy 'config_template.yml' file to 'config.yml' and fill in the missing values
#

##################################################
#
# Required values
#
##################################################

# (REQUIRED) 53
gcsv5_version:

# (REQUIRED) Production|Preview|Staging|Test|Integration|Sandbox
globus_environment:

# (REQUIRED) String
gcsv5_client_id:

# (REQUIRED) String
gcsv5_client_secret:

# (REQUIRED) String
lets_encrypt_email:

#
# globus_domain will be the domain set on the storage gateways.
#

# (REQUIRED) String
globus_domain:

#
# globus_identity must be an identity with the same domain as the domain
# used on the storage gateways
#

# (REQUIRED) String
globus_identity:

# (REQUIRED) String
local_username:

##################################################
#
# Optional values
#
##################################################

# (OPTIONAL) String
endpoint_name:

# (OPTIONAL) String
endpoint_server_name:

# (OPTIONAL) String
endpoint_admin:

##################################################
#
# These are filled in by the helper scripts
#
##################################################

__native_app__: &native_app
  id:
  secret:

__tokens__:
- grant_type: authorization_code
  scopes:
  - name: urn:globus:auth:scope:transfer.api.globus.org:all
  - name: urn:globus:auth:scope:{{ gcsv5_client_id }}:manage_collections
  access_type: offline
  client:
    <<: *native_app
  tokens: {}
