#
# Copy 'config_template.yml' file to 'config.yml' and fill in the missing values
#

##################################################
#
# Required values
#
##################################################

# (REQUIRED) 53
gcsv5_version: 

# (REQUIRED) Production|Preview|Staging|Test|Integration|Sandbox
globus_environment: 

# (REQUIRED) String
gcsv5_client_id: 

# (REQUIRED) String
gcsv5_client_secret: 

# (REQUIRED) String
lets_encrypt_email: 

##################################################
#
# Optional values
#
##################################################

# (OPTIONAL) String
endpoint_name:

# (OPTIONAL) String
endpoint_server_name:

# (OPTIONAL) String
endpoint_admin:

##################################################
#
# These are filled in by the helper scripts
#
##################################################

# (Placeholdr)
app_client_id:

# (Placeholdr)
app_client_secret:

# (Placeholdr)
transfer_access_token:

# (Placeholdr)
transfer_refresh_token:

# (Placeholdr)
gcs_manager_access_token:

# (Placeholdr)
gcs_manager_refresh_token:
