---

- name: '[Gateways] Query current gateway definitions'
  become:  yes
  command: /usr/sbin/globus-connect-server-config storage-gateway list
  register: gateway_list
  when:
    - gcs.gateways is defined

- name: '[Gateways] Create missing storage gateways'
  become: yes
  vars:
  command: >
        /usr/sbin/globus-connect-server-config storage-gateway create
        --root {{ item.root }}
        --connector {{ item.connector }}
        --display-name "{{ item.display_name }}"

        {% if item.high_assurance is defined and item.high_assurance|bool %}
        --high-assurance
        --authentication-assurance-timeout {{ item.authentication_assurance_timeout }}
        {% endif %}

        --domain {{ item.domain }}

        {% if item.identify_provider is defined %}
          {% if item.identify_provider %}
          --identity-provider {{ item.identity_provider }}
          {% endif %}
        {% endif %}

        {% if item.restrict_paths is defined %}
          {% if item.restrict_paths %}
            --restrict-paths {{ item.restrict_paths }}
          {% endif %}
        {% endif %}

        --{{ item.mapped_collections }}-mapped-collections
        --{{ item.guest_collections }}-guest-collections

        {% if item.connector == 'Box' %}
        --box-json-config {{ item.box.box_json_config }}
        {% endif %}

        {% if item.connector == 'BlackPearl' %}
        --bp-access-id-file {{ item.blackpearl.bp_access_id_file }}
        --s3_endpoint       {{ item.blackpearl.s3_endpoint }}
        {% endif %}

        {% if item.connector == 'Ceph' %}
        --ceph-admin-key-id     {{ item.ceph.ceph_admin_key_id }}
        --ceph-admin-secret-key {{ item.ceph.ceph_admin_secrety_key }}
        --s3-endpoint           {{ item.ceph.s3_endpoint }}
          {% if item.ceph.s3_bucket is defined %}
          {% if item.ceph.s3_bucket %}
          --s3-bucket
          {% endif %}
          {% endif %}
        {% endif %}

        {% if item.connector == 'Google Drive' %}
        --client-id     {{ item.google_drive.client_id }}
        --client-secret {{ item.google_drive.client_secret }}

          {% if item.google_drive.user_api_rate_quota is defined %}
          {% if item.google_drive.user_api_rate_quota %}
          --user-api-rate-quota {{ item.google_drive.user_api_rate_quota }}
          {% endif %}
          {% endif %}
        {% endif %}

        {% if item.connector == 'Google Cloud Storage' %}
        --client-id     {{ item.google_cloud_storage.client_id }}
        --client-secret {{ item.google_cloud_storage.client_secret }}
        {% endif %}

        {% if item.connector == 'POSIX' %}
          {% if item.posix.users_allow is defined %}
          {% if item.posix.users_allow %}
          --users-allow {{ item.posix.users_allow }}
          {% endif %}
          {% endif %}

          {% if item.posix.users_deny is defined %}
          {% if item.posix.users_deny %}
          --users-deny {{ item.posix.users_deny }}
          {% endif %}
          {% endif %}

          {% if item.posix.groups_allow is defined %}
          {% if item.posix.groups_allow %}
          --groups-allow {{ item.posix.groups_allow }}
          {% endif %}
          {% endif %}

          {% if item.posix.groups_deny is defined %}
          {% if item.posix.groups_deny %}
          --groups-deny {{ item.posix.groups_deny }}
          {% endif %}
          {% endif %}
        {% endif %}

        {% if item.connector == 'S3' %}
        --s3-endpoint {{ item.s3.s3_endpoint }}

          {% if item.s3.s3_user_credentials is defined %}
          {% if item.s3.s3_user_credentials %}
          --s3-user-credential
          {% else %}
          --s3-unauthenticated
          {% endif %}
          {% else %}
          --s3-unauthenticated
          {% endif %}

          {% if item.s3.s3_bucket is defined %}
          {% if item.s3.s3_bucket %}
          --s3-bucket {{ item.s3.s3_bucket }}
          {% endif %}
          {% endif %}
        {% endif %}


  loop: "{{ gcs.gateways if gcs.gateways != None else [] }}"
  when: 
    - gcs.gateways is defined
    - "'| '~item.display_name~' |' not in gateway_list.stdout"


