
GLOBUS_CONNECT_SERVER:
  #
  # GCSv5 version to install
  #

  # (REQUIRED) 52|53
  version:

  #
  # Globus software environment to deploy in.
  #

  # (REQUIRED) Production|Preview|Staging|Test|Integration|Sandbox
  environment:

  #
  # See /etc/globus-connect-server.conf for details on these options.
  #

  # (REQUIRED) String
  client_id:

  # (REQUIRED) String
  client_secret:

  # (REQUIRED) String
  lets_encrypt_email:

  # (OPTIONAL) String
  endpoint_name:

  # (OPTIONAL) String
  endpoint_server_name:

  #
  # See /sbin/globus-connect-server-config endpoint admin add-role
  #

  # (OPTIONAL) String
  # Set this user identity as an admin of the endpoint
  endpoint_admin:

  #
  # Used with the Transfer API to set the endpoint as managed. Requires scope
  # 'urn:globus:auth:scope:transfer.api.globus.org:all'
  #

  # (REQUIRED) String
  transfer_refresh_token:

  #
  # Used with the GCS manager API to create guest collections. Requires scope
  # 'https://auth.globus.org/scopes/<gcs manager uuid>/manage_collections'
  #

  # (REQUIRED) String
  gcs_manager_refresh_token:

  #
  # The Globus Auth client ID and secret used to generate the refresh tokens.
  # This is used when refreshing access tokens.
  #

  # (REQUIRED) String
  app_client_id:

  # (REQUIRED) String
  app_client_secret:

  # (OPTIONAL) List of storage-gateways for this endpoint
  gateways:
    # '-' will start a new storage gateway definition
    -
      #
      # See /sbin/globus-connect-server-config storage-gateway create
      #

      # (REQUIRED) String
      root:
 
      # (REQUIRED) 
      # Box|BlackPearl|Ceph|Google Drive|Google Cloud Storage|POSIX|S3
      connector:
 
      # (REQUIRED) String
      display_name:

      # (OPTIONAL) True|False  Default:False
      high_assurance:

      # (OPTIONAL) Number (required when high_assurance = True)
      authentication_assurance_timeout:

      # (REQUIRED) String
      domain:

      # (Optional) String
      identity_provider:

      # (Optional) String
      restrict_paths:

      # (Required) allow|disallow
      guest_collections:

      # (Required) allow|disallow
      mapped_collections:

      #
      # Box Connector Options
      #
      box:
        # (REQUIRED) String
        box_json_config:

      # 
      # BlackPearl Connector Options
      # 
      blackpearl:
        # (REQUIRED) String
        bp_access_id_file:
        # (REQUIRED) String
        s3_endpoint:

      #
      # Ceph Connector Options
      #
      ceph:
         # (REQUIRED) String
         ceph_admin_key_id:
         # (REQUIRED) String
         ceph_admin_secret_key:
         # (REQUIRED) String
         s3_endpoint:
         # (OPTIONAL) String
         s3_bucket:

      #
      # Google Drive Connector Options
      #
      google_drive:
        # (REQUIRED) String
        client_id:
        # (REQUIRED) String
        client_secret:
        # (OPTIONAL) String
        user_api_rate_quota:

      #
      # Google Cloud Connector Options
      #
      google_cloud_storage:
        # (REQUIRED) String
        client_id:
        # (REQUIRED) String
        client_secret:
        # (OPTIONAL) List (Not implemented)
        google_cloud_storage_project:
        # (OPTIONAL) List (Not implemented)
        google-cloud-storage-bucket:

      #
      # POSIX Connector Options
      #
      posix:
        # (OPTIONAL) String
        users_allow:

        # (OPTIONAL) String
        users_deny:

        # (OPTIONAL) String
        groups_allow:

        # (OPTIONAL) String
        groups_deny:

      #
      # S3 Connector Options
      #
      s3:
         # (REQUIRED) String
         s3_endpoint:
         # (Optional) String
         s3_user_credentials:
         # (OPTIONAL) String
         s3_bucket:

      collections:
        # '-' will start a new collection definition
        -
          # (REQUIRED) mapped|guest
          type:

          # Guest collection options.
          guest:
            # (REQUIRED) String (ex 'jasonalt@globus.org')
            user_auth_identity:

            # (REQUIRED) String. Must be a valid account.
            local_username:

          # (REQUIRED) String
          display_name:
          
          # (OPTIONAL)
          root:

          # (OPTIONAL)
          default_directory:

          # (OPTIONAL)
          acls:
            # '-' will start a new acl definition
            -
              # (REQUIRED) identity|group|all_authenticated_users|anonymous
              principal_type: 

              # (REQUIRED) uuid if principal_type=identity or group
              principal: 

              # (REQUIRED) String
              path:

              # (REQUIRED) r|rw
              permissions: 

              # (OPTIONAL) String
              notify_email: 

              # (OPTIONAL) String. Requires notify_email
              notify_message: 
